### ISSUE TITLE
[Freemium Music][v0.6]The app unable  to open download folder.

### ISSUE THREAD

**Issue by masudr4n4** [NitishGadangi/Freemium-App#1]
<h4>Actual Behaviour </h4>
The app unable to open Download folder in file manager.Storage permission granted but seems the app could not find fil manager app in my device thats why telling to install a file manager.
<h4>Expected behavior</h4>
Expected that the can open the Download Folders directly after clicking Open Download Folder..</h4>
<h4>Step to reproduce </h4>
<ol>
<li><a href="https://www.mediafire.com/file/79nwirbj2vvunjg/Freemium_Music_v0.6Beta.apk/file">Install</a> beta version and open the app</li>
<li>Search any song and download a song to create a folder in file manager.</li>
<li>After successfully download a song ,click Downloads</li>
<li>Click open Downloads Folder</li>
<li> see error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v1.0</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/KIARQRiFjRY">https://youtu.be/KIARQRiFjRY</a>

**Comment by maaudrana** [comment]
@NitishGadangi you there?

**Comment by NitishGadangi** [comment]
For now...
Please try installing
Es explorer or Solid file manager.
Sorry for the late reply

And
Tnx for considering to report the issue..👍🏻

**Comment by masudr4n4** [comment]
Oh i see working  its working  with solid explorer file manager but should  work with device default  file manager.

**Comment by NitishGadangi** [comment]
Yeah found a way to make it work
And will solve that issue in next build..

Hope You enjoy the app

**Comment by masudr4n4** [comment]
Yeah! Really  enjoyed .tnx

**Comment by NitishGadangi** [comment]
A temporary workaround is to use a third-party file manager like **es-explorer or solid file manager**
Possibility for opening in default file browser will be added in next build.
So this issue is closed for now.
